#
#                       o   o                            
#                       8                                
# .oPYo. .oPYo. odYo.  o8P o8 .oPYo. odYo. .oPYo. .oPYo. 
# Yb..   8oooo8 8' `8   8   8 8oooo8 8' `8 8    ' 8oooo8 
#   'Yb. 8.     8   8   8   8 8.     8   8 8    . 8.     
# `YooP' `Yooo' 8   8   8   8 `Yooo' 8   8 `YooP' `Yooo' 
# :.....::.....:..::..::..::..:.....:..::..:.....::.....:
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#   Copyright Yazan Obeidi, 2017
#
#   docker compose - development
#
version: '3.3'
services:
    sentience-base:
        build:  .
    executor:
        build: ./executor/
        depends_on:
          - sentience-base
        volumes:
          - /home/yazan/Projects/sentience:/sentience   
    interactor:
        build: ./interactor/
        depends_on:
          - sentience-base
        volumes:
          - /home/yazan/Projects/sentience:/sentience
    zookeeper:
        image: ./zookeeper/zookeeper-docker/
        ports:
          - "2181:2181"
    kafka:
        build: ./kafka/
        ports:
          - "9092"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock