#
#                       o   o                            
#                       8                                
# .oPYo. .oPYo. odYo.  o8P o8 .oPYo. odYo. .oPYo. .oPYo. 
# Yb..   8oooo8 8' `8   8   8 8oooo8 8' `8 8    ' 8oooo8 
#   'Yb. 8.     8   8   8   8 8.     8   8 8    . 8.     
# `YooP' `Yooo' 8   8   8   8 `Yooo' 8   8 `YooP' `Yooo' 
# :.....::.....:..::..::..::..:.....:..::..:.....::.....:
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#   Copyright Yazan Obeidi, 2017
#
#   docker compose - production
#
version: '3.3'
services:
    kafka:
        build: ./kafka/docker-kafka/
        ports:
          - "2181:2181"
          - "9092:9092"
    sentience-base:
        build:  .
        depends_on:
          - kafka
    executor:
        build: ./executor/
        depends_on:
          - sentience-base
    interactor:
        build: ./interactor/
        depends_on:
          - sentience-base